# DAV ASSIGNMENT1
Dipean Dasgupta
202151188

**Importing libraries**

In [ ]:
import pandas as pd
import json

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Reading files**

In [ ]:
Data=pd.read_csv("/content/drive/MyDrive/CS312_DA/district_level_service_msme.csv")

In [ ]:
filepath="/content/drive/MyDrive/CS312_DA/district_level_manufacturing_msme.json"
f=open(filepath)
Data2= json.load(f)

In [ ]:
Data.head()

,STATE_NAME,Lg_Dist_Code,DISTRICT_NAME,MICRO,SMALL,MEDIUM,Total,Last_Updated
0,ANDHRA PRADESH,502,ANANTHAPUR,7797,238,10,8045,2022-01-11
1,ANDHRA PRADESH,503,CHITOOR,9623,351,19,9993,2022-01-11
2,ANDHRA PRADESH,505,EAST GODAVARI,12347,615,49,13011,2022-01-11
3,ANDHRA PRADESH,506,GUNTUR,11386,630,53,12069,2022-01-11
4,ANDHRA PRADESH,510,KRISHNA,15189,1007,79,16275,2022-01-11

**Task1:Create two data frames by reading above two files.**

In [ ]:
df1=pd.DataFrame(Data)
df1

,STATE_NAME,Lg_Dist_Code,DISTRICT_NAME,MICRO,SMALL,MEDIUM,Total,Last_Updated
0,ANDHRA PRADESH,502,ANANTHAPUR,7797,238,10,8045,2022-01-11
1,ANDHRA PRADESH,503,CHITOOR,9623,351,19,9993,2022-01-11
2,ANDHRA PRADESH,505,EAST GODAVARI,12347,615,49,13011,2022-01-11
3,ANDHRA PRADESH,506,GUNTUR,11386,630,53,12069,2022-01-11
4,ANDHRA PRADESH,510,KRISHNA,15189,1007,79,16275,2022-01-11
...,...,...,...,...,...,...,...,...
733,LAKSHADWEEP,553,LAKSHADWEEP DISTRICT,114,0,0,114,2022-01-11
734,PUDUCHERRY,598,KARAIKAL,989,47,1,1037,2022-01-11
735,PUDUCHERRY,599,MAHE,71,11,0,82,2022-01-11
736,PUDUCHERRY,600,PONDICHERRY,5577,202,21,5800,2022-01-11
737,PUDUCHERRY,601,YANAM,65,6,0,71,2022-01-11

In [ ]:
df2=pd.DataFrame(Data2["data"])
df2

,0,1,2,3,4,5,6,7
0,ANDHRA PRADESH,502,ANANTHAPUR,11370,483,33,11886,2022-01-11
1,ANDHRA PRADESH,503,CHITOOR,13037,592,51,13680,2022-01-11
2,ANDHRA PRADESH,505,EAST GODAVARI,16711,1044,123,17878,2022-01-11
3,ANDHRA PRADESH,506,GUNTUR,15955,1678,169,17802,2022-01-11
4,ANDHRA PRADESH,510,KRISHNA,20460,1673,165,22298,2022-01-11
...,...,...,...,...,...,...,...,...
732,LADAKH,9,LEH LADAKH,1493,35,0,1528,2022-01-11
733,LAKSHADWEEP,553,LAKSHADWEEP DISTRICT,150,0,0,150,2022-01-11
734,PUDUCHERRY,598,KARAIKAL,1248,56,2,1306,2022-01-11
735,PUDUCHERRY,599,MAHE,95,17,0,112,2022-01-11
736,PUDUCHERRY,600,PONDICHERRY,7698,413,50,8161,2022-01-11

In [ ]:
colms=[dic["label"] for dic in Data2["fields"]]
print(colms)
df3=pd.DataFrame(Data2["data"],columns=colms)
df3

['STATE_NAME', 'Lg_Dist_Code', 'DISTRICT_NAME', 'MICRO', 'SMALL', 'MEDIUM', 'Total', 'Last_Updated']

,STATE_NAME,Lg_Dist_Code,DISTRICT_NAME,MICRO,SMALL,MEDIUM,Total,Last_Updated
0,ANDHRA PRADESH,502,ANANTHAPUR,11370,483,33,11886,2022-01-11
1,ANDHRA PRADESH,503,CHITOOR,13037,592,51,13680,2022-01-11
2,ANDHRA PRADESH,505,EAST GODAVARI,16711,1044,123,17878,2022-01-11
3,ANDHRA PRADESH,506,GUNTUR,15955,1678,169,17802,2022-01-11
4,ANDHRA PRADESH,510,KRISHNA,20460,1673,165,22298,2022-01-11
...,...,...,...,...,...,...,...,...
732,LADAKH,9,LEH LADAKH,1493,35,0,1528,2022-01-11
733,LAKSHADWEEP,553,LAKSHADWEEP DISTRICT,150,0,0,150,2022-01-11
734,PUDUCHERRY,598,KARAIKAL,1248,56,2,1306,2022-01-11
735,PUDUCHERRY,599,MAHE,95,17,0,112,2022-01-11
736,PUDUCHERRY,600,PONDICHERRY,7698,413,50,8161,2022-01-11

**Task2:Find out total ”Small” Manufacturing MSME in India.**

In [ ]:
df3['SMALL']=df3['SMALL'].astype(int)
Small_total= df3['SMALL'].sum()
print("Total 'Small' Manufacturing MSMEs in India:", Small_total)

Total 'Small' Manufacturing MSMEs in India: 317222

**Task3:  Create a dataframe having a state wise total number of ”Micro”,”Small” and ”Medium” Services MSE (as shown below) and save the results as a CSV file.**

In [ ]:
df3['MICRO']=df3['MICRO'].astype(int)
df3['MEDIUM']=df3['MEDIUM'].astype(int)
df_state_totals = df3.groupby('STATE_NAME',as_index=False).agg({
    'MICRO': 'sum',
    'SMALL': 'sum',
    'MEDIUM': 'sum'
})
print(df_state_totals.to_string(index=False))
df_state_totals.to_csv('state_wise_total.csv',index=False)

                 STATE_NAME   MICRO  SMALL  MEDIUM
ANDAMAN AND NICOBAR ISLANDS    3905    140       7
             ANDHRA PRADESH  153814  10599    1030
          ARUNACHAL PRADESH    2172     99      11
                      ASSAM   65544   3345     309
                      BIHAR  247394   5226     413
                 CHANDIGARH   11435   1007     134
               CHHATTISGARH   74058   4580     566
     DADAR AND NAGAR HAVELI    3730    419      82
              DAMAN AND DIU    1626    295      56
                      DELHI  166761  19400    2594
                        GOA   11556    713      91
                    GUJARAT  496564  38098    4168
                    HARYANA  213404  16387    1696
           HIMACHAL PRADESH   28509   1559     238
          JAMMU AND KASHMIR   73438   1854     148
                  JHARKHAND   97726   3492     308
                  KARNATAKA  350026  18996    2106
                     KERALA  147692   8856     785
                     LADAKH    2340     49       0
                LAKSHADWEEP     150      0       0
             MADHYA PRADESH  264197  12190    1045
                MAHARASHTRA 1305092  49991    6377
                    MANIPUR   21076    247      10
                  MEGHALAYA    1828    147      21
                    MIZORAM    2942     74       8
                   NAGALAND    2875     53       4
                     ODISHA  116968   5412     463
                 PUDUCHERRY    9041    486      52
                     PUNJAB  212134  12334    1269
                  RAJASTHAN  501175  19456    1672
                     SIKKIM    1382     56       8
                 TAMIL NADU  668147  30634    2879
                  TELANGANA  199030  12540    1649
                    TRIPURA    6103    252      17
              UTTAR PRADESH  486415  21530    2112
                UTTARAKHAND   54666   2618     283
                WEST BENGAL  167593  14088    1631

In [ ]:
df3['Lg_Dist_Code'] = df3['Lg_Dist_Code'].astype(int)
df3['Last_Updated'] = pd.to_datetime(df3['Last_Updated'])
df1['Last_Updated'] = pd.to_datetime(df1['Last_Updated'])

 **Task4: Join the both the data frame based on common STATE NAME, DISTRICT NAME, Lg Dist Code and Last Updated. The result should look like below. ”x” and ”y” in the image below represent the manufacturing MSME and service MSME respectively.**

In [ ]:
dfm = pd.merge(df1, df3, on=['STATE_NAME', 'DISTRICT_NAME', 'Lg_Dist_Code', 'Last_Updated'])
dfm

,STATE_NAME,Lg_Dist_Code,DISTRICT_NAME,MICRO_x,SMALL_x,MEDIUM_x,Total_x,Last_Updated,MICRO_y,SMALL_y,MEDIUM_y,Total_y
0,ANDHRA PRADESH,502,ANANTHAPUR,7797,238,10,8045,2022-01-11,11370,483,33,11886
1,ANDHRA PRADESH,503,CHITOOR,9623,351,19,9993,2022-01-11,13037,592,51,13680
2,ANDHRA PRADESH,505,EAST GODAVARI,12347,615,49,13011,2022-01-11,16711,1044,123,17878
3,ANDHRA PRADESH,506,GUNTUR,11386,630,53,12069,2022-01-11,15955,1678,169,17802
4,ANDHRA PRADESH,510,KRISHNA,15189,1007,79,16275,2022-01-11,20460,1673,165,22298
...,...,...,...,...,...,...,...,...,...,...,...,...
732,LADAKH,9,LEH LADAKH,1099,23,0,1122,2022-01-11,1493,35,0,1528
733,LAKSHADWEEP,553,LAKSHADWEEP DISTRICT,114,0,0,114,2022-01-11,150,0,0,150
734,PUDUCHERRY,598,KARAIKAL,989,47,1,1037,2022-01-11,1248,56,2,1306
735,PUDUCHERRY,599,MAHE,71,11,0,82,2022-01-11,95,17,0,112
736,PUDUCHERRY,600,PONDICHERRY,5577,202,21,5800,2022-01-11,7698,413,50,8161

**Task5:
Create a Pivot Table having rows STATE NAME and columns Service and Manufacturing ”MSME”. Use ”Sum” to add up district wise numbers.**

In [ ]:
df_pivot = dfm[['STATE_NAME', 'MICRO_x', 'MICRO_y', 'SMALL_x', 'SMALL_y', 'MEDIUM_x', 'MEDIUM_y']]
pivot_table = df_pivot.pivot_table(index='STATE_NAME', aggfunc='sum')

In [ ]:
pivot_table_reset = pivot_table.reset_index()

In [ ]:
print(pivot_table_reset.to_string(index=False))

                 STATE_NAME  MEDIUM_x  MEDIUM_y  MICRO_x  MICRO_y  SMALL_x  SMALL_y
ANDAMAN AND NICOBAR ISLANDS         6         7     2884     3905      111      140
             ANDHRA PRADESH       422      1030   115320   153814     5799    10599
          ARUNACHAL PRADESH         6        11     1201     2172       53       99
                      ASSAM       200       309    41051    65544     2182     3345
                      BIHAR       245       413   167835   247394     3908     5226
                 CHANDIGARH        76       134     9010    11435      687     1007
               CHHATTISGARH       257       566    58905    74058     2726     4580
     DADAR AND NAGAR HAVELI         3        82     2511     3730       98      419
              DAMAN AND DIU         2        56      892     1626       35      295
                      DELHI      1399      2594   106599   166761    10080    19400
                        GOA        40        91     8963    11556      428      713
                    GUJARAT      1164      4168   283123   496564    12067    38098
                    HARYANA       582      1696   147956   213404     7231    16387
           HIMACHAL PRADESH        26       238    21730    28509      613     1559
          JAMMU AND KASHMIR        62       148    47434    73438     1145     1854
                  JHARKHAND       170       308    74753    97726     2357     3492
                  KARNATAKA       987      2106   248728   350026    10468    18996
                     KERALA       397       785    98110   147692     5305     8856
                     LADAKH         0         0     1652     2340       32       49
                LAKSHADWEEP         0         0      114      150        0        0
             MADHYA PRADESH       397      1045   194520   264197     6634    12190
                MAHARASHTRA      2797      6377   962520  1305092    25367    49991
                    MANIPUR         9        10    10051    21076      175      247
                  MEGHALAYA        11        21     1286     1828       89      147
                    MIZORAM         8         8     2002     2942       52       74
                   NAGALAND         2         4     1757     2875       23       53
                     ODISHA       281       463    87502   116968     3798     5412
                 PUDUCHERRY        22        52     6637     9041      260      486
                     PUNJAB       337      1269   141714   212134     5021    12334
                  RAJASTHAN       616      1672   328406   501175     8952    19456
                     SIKKIM         8         8     1073     1382       39       56
                 TAMIL NADU      1050      2879   431053   668147    13954    30634
                  TELANGANA       713      1649   150812   199030     6783    12540
                    TRIPURA         9        17     3556     6103      163      252
              UTTAR PRADESH       914      2112   326045   486415    11567    21530
                UTTARAKHAND        79       283    39722    54666     1237     2618
                WEST BENGAL       772      1631   111856   167593     7657    14088