# **DAV ASSIGNMENT 6**
**Dipean Dasgupta<br>
202151188**

# Data Access

**Importing Libraries**

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

**Connecting Gdrive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Loading Data**

In [ ]:
DS1=pd.read_csv('/content/drive/MyDrive/CS312_DA/population_of_female.csv')
DS2=pd.read_csv('/content/drive/MyDrive/CS312_DA/primary_completion_rate_female.csv')

**Overview of the Data**

In [ ]:
DS1.head()

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Last Updated Date,12/22/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
4,Aruba,ABW,Population female,SP.POP.TOTL.FE.IN,27773.0,28380.0,28820.0,29218.0,29570.0,29875.0,...,53480.0,53953.0,54403.0,54828.0,55224.0,55591.0,55935.0,56254.0,56373.0,56330.0

In [ ]:
DS2.head()

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Last Updated Date,12/22/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2012.0,2013.000000,2014.00000,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
4,Aruba,ABW,Primary completion rate female (% of relevant ...,SE.PRM.CMPT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,101.255234,101.55587,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Data Cleaning

In [ ]:
DS1='/content/drive/MyDrive/CS312_DA/population_of_female.csv'
DF1=pd.read_csv(DS1, header=2, skiprows=[0, 1])

In [ ]:
DF1.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,Population female,SP.POP.TOTL.FE.IN,27773.0,28380.0,28820.0,29218.0,29570.0,29875.0,...,53480.0,53953.0,54403.0,54828.0,55224.0,55591.0,55935.0,56254.0,56373.0,56330.0
1,Africa Eastern and Southern,AFE,Population female,SP.POP.TOTL.FE.IN,65853220.0,67606287.0,69457112.0,71375643.0,73386167.0,75478396.0,...,279546577.0,287224786.0,295088995.0,303195759.0,311387262.0,319637226.0,328158974.0,336930831.0,345889729.0,354855082.0
2,Afghanistan,AFG,Population female,SP.POP.TOTL.FE.IN,4145945.0,4233771.0,4326881.0,4424511.0,4526691.0,4634341.0,...,15067373.0,15594637.0,16172321.0,16682054.0,17115346.0,17614722.0,18136922.0,18679089.0,19279930.0,19844584.0
3,Africa Western and Central,AFW,Population female,SP.POP.TOTL.FE.IN,48802898.0,49850088.0,50928609.0,52044907.0,53196730.0,54389295.0,...,187755307.0,192900081.0,198163527.0,203513873.0,208980433.0,214578994.0,220253839.0,226004857.0,231877590.0,237813580.0
4,Angola,AGO,Population female,SP.POP.TOTL.FE.IN,2670229.0,2704394.0,2742689.0,2779473.0,2812590.0,2838939.0,...,12770743.0,13252938.0,13746371.0,14248799.0,14764575.0,15293335.0,15828040.0,16370553.0,16910989.0,17452283.0

In [ ]:
DS2='/content/drive/MyDrive/CS312_DA/primary_completion_rate_female.csv'
DF2=pd.read_csv(DS2, header=2, skiprows=[0, 1])

In [ ]:
DF2.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,Primary completion rate female (% of relevant ...,SE.PRM.CMPT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,101.255234,101.55587,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Primary completion rate female (% of relevant ...,SE.PRM.CMPT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,65.88575,66.028069,66.26329,66.115013,66.932449,68.167793,69.499100,69.990547,70.825378,NaN
2,Afghanistan,AFG,Primary completion rate female (% of relevant ...,SE.PRM.CMPT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,63.604069,66.688881,67.129303,65.761513,NaN,NaN
3,Africa Western and Central,AFW,Primary completion rate female (% of relevant ...,SE.PRM.CMPT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.04483,64.063690,64.65110,65.822060,66.608093,66.362289,66.722877,66.927361,67.231689,NaN
4,Angola,AGO,Primary completion rate female (% of relevant ...,SE.PRM.CMPT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
DF1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 66 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            264 non-null    float64
 5   1961            264 non-null    float64
 6   1962            264 non-null    float64
 7   1963            264 non-null    float64
 8   1964            264 non-null    float64
 9   1965            264 non-null    float64
 10  1966            264 non-null    float64
 11  1967            264 non-null    float64
 12  1968            264 non-null    float64
 13  1969            264 non-null    float64
 14  1970            264 non-null    float64
 15  1971            264 non-null    float64
 16  1972            264 non-null    float64
 17  1973            264 non-null    float64
 18  1974            264 non-null    float64
 19  1975            264 non-null    float64
 20  1976            264 non-null    float64
 21  1977            264 non-null    float64
 22  1978            264 non-null    float64
 23  1979            264 non-null    float64
 24  1980            264 non-null    float64
 25  1981            264 non-null    float64
 26  1982            264 non-null    float64
 27  1983            264 non-null    float64
 28  1984            264 non-null    float64
 29  1985            264 non-null    float64
 30  1986            264 non-null    float64
 31  1987            264 non-null    float64
 32  1988            264 non-null    float64
 33  1989            264 non-null    float64
 34  1990            265 non-null    float64
 35  1991            265 non-null    float64
 36  1992            265 non-null    float64
 37  1993            265 non-null    float64
 38  1994            265 non-null    float64
 39  1995            265 non-null    float64
 40  1996            265 non-null    float64
 41  1997            265 non-null    float64
 42  1998            265 non-null    float64
 43  1999            265 non-null    float64
 44  2000            265 non-null    float64
 45  2001            265 non-null    float64
 46  2002            265 non-null    float64
 47  2003            265 non-null    float64
 48  2004            265 non-null    float64
 49  2005            265 non-null    float64
 50  2006            265 non-null    float64
 51  2007            265 non-null    float64
 52  2008            265 non-null    float64
 53  2009            265 non-null    float64
 54  2010            265 non-null    float64
 55  2011            265 non-null    float64
 56  2012            265 non-null    float64
 57  2013            265 non-null    float64
 58  2014            265 non-null    float64
 59  2015            265 non-null    float64
 60  2016            265 non-null    float64
 61  2017            265 non-null    float64
 62  2018            265 non-null    float64
 63  2019            265 non-null    float64
 64  2020            265 non-null    float64
 65  2021            265 non-null    float64
dtypes: float64(62), object(4)
memory usage: 137.3+ KB

In [ ]:
DF2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 66 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            27 non-null     float64
 15  1971            66 non-null     float64
 16  1972            81 non-null     float64
 17  1973            84 non-null     float64
 18  1974            88 non-null     float64
 19  1975            89 non-null     float64
 20  1976            99 non-null     float64
 21  1977            101 non-null    float64
 22  1978            102 non-null    float64
 23  1979            98 non-null     float64
 24  1980            100 non-null    float64
 25  1981            105 non-null    float64
 26  1982            101 non-null    float64
 27  1983            105 non-null    float64
 28  1984            107 non-null    float64
 29  1985            102 non-null    float64
 30  1986            101 non-null    float64
 31  1987            110 non-null    float64
 32  1988            111 non-null    float64
 33  1989            103 non-null    float64
 34  1990            96 non-null     float64
 35  1991            100 non-null    float64
 36  1992            113 non-null    float64
 37  1993            111 non-null    float64
 38  1994            115 non-null    float64
 39  1995            112 non-null    float64
 40  1996            113 non-null    float64
 41  1997            104 non-null    float64
 42  1998            106 non-null    float64
 43  1999            163 non-null    float64
 44  2000            167 non-null    float64
 45  2001            168 non-null    float64
 46  2002            172 non-null    float64
 47  2003            164 non-null    float64
 48  2004            170 non-null    float64
 49  2005            174 non-null    float64
 50  2006            162 non-null    float64
 51  2007            170 non-null    float64
 52  2008            176 non-null    float64
 53  2009            176 non-null    float64
 54  2010            174 non-null    float64
 55  2011            178 non-null    float64
 56  2012            185 non-null    float64
 57  2013            187 non-null    float64
 58  2014            188 non-null    float64
 59  2015            181 non-null    float64
 60  2016            184 non-null    float64
 61  2017            179 non-null    float64
 62  2018            178 non-null    float64
 63  2019            180 non-null    float64
 64  2020            162 non-null    float64
 65  2021            65 non-null     float64
dtypes: float64(62), object(4)
memory usage: 137.3+ KB

In [ ]:
DF2.drop(columns=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969'], inplace=True) #dropping columns with full null values

In [ ]:
DF2.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,Primary completion rate female (% of relevant ...,SE.PRM.CMPT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,101.255234,101.55587,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Primary completion rate female (% of relevant ...,SE.PRM.CMPT.FE.ZS,NaN,NaN,NaN,36.464031,37.446320,38.355099,...,65.88575,66.028069,66.26329,66.115013,66.932449,68.167793,69.499100,69.990547,70.825378,NaN
2,Afghanistan,AFG,Primary completion rate female (% of relevant ...,SE.PRM.CMPT.FE.ZS,NaN,NaN,NaN,NaN,4.361800,NaN,...,NaN,NaN,NaN,NaN,63.604069,66.688881,67.129303,65.761513,NaN,NaN
3,Africa Western and Central,AFW,Primary completion rate female (% of relevant ...,SE.PRM.CMPT.FE.ZS,NaN,NaN,45.455502,45.485439,45.263828,45.920872,...,64.04483,64.063690,64.65110,65.822060,66.608093,66.362289,66.722877,66.927361,67.231689,NaN
4,Angola,AGO,Primary completion rate female (% of relevant ...,SE.PRM.CMPT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pof= pd.DataFrame(DF1)
pcrf=pd.DataFrame(DF2)

# LAB TASK

**TASK1:**<br>
**Create a column named “average_rate” in “primary_completion_rate_female.csv” that
contains the average (over years) completion rate for each country.**

In [ ]:
# Defining a custom function to fill null values with row means for numeric columns only
def fill_null_with_row_mean(row):
    num_val = pd.to_numeric(row, errors='coerce')
    if num_val.notnull().any():
        r_mean = num_val.mean()
        row.fillna(r_mean, inplace=True)  #fill the null places with mean of that row
    return row

pcrf = pcrf.apply(fill_null_with_row_mean, axis=1)

In [ ]:
pcrf['average_rate'] = pcrf.iloc[:, 4:].mean(axis=1, skipna=True)

In [ ]:
pcrf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 57 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1970            245 non-null    float64
 5   1971            245 non-null    float64
 6   1972            245 non-null    float64
 7   1973            245 non-null    float64
 8   1974            245 non-null    float64
 9   1975            245 non-null    float64
 10  1976            245 non-null    float64
 11  1977            245 non-null    float64
 12  1978            245 non-null    float64
 13  1979            245 non-null    float64
 14  1980            245 non-null    float64
 15  1981            245 non-null    float64
 16  1982            245 non-null    float64
 17  1983            245 non-null    float64
 18  1984            245 non-null    float64
 19  1985            245 non-null    float64
 20  1986            245 non-null    float64
 21  1987            245 non-null    float64
 22  1988            245 non-null    float64
 23  1989            245 non-null    float64
 24  1990            245 non-null    float64
 25  1991            245 non-null    float64
 26  1992            245 non-null    float64
 27  1993            245 non-null    float64
 28  1994            245 non-null    float64
 29  1995            245 non-null    float64
 30  1996            245 non-null    float64
 31  1997            245 non-null    float64
 32  1998            245 non-null    float64
 33  1999            245 non-null    float64
 34  2000            245 non-null    float64
 35  2001            245 non-null    float64
 36  2002            245 non-null    float64
 37  2003            245 non-null    float64
 38  2004            245 non-null    float64
 39  2005            245 non-null    float64
 40  2006            245 non-null    float64
 41  2007            245 non-null    float64
 42  2008            245 non-null    float64
 43  2009            245 non-null    float64
 44  2010            245 non-null    float64
 45  2011            245 non-null    float64
 46  2012            245 non-null    float64
 47  2013            245 non-null    float64
 48  2014            245 non-null    float64
 49  2015            245 non-null    float64
 50  2016            245 non-null    float64
 51  2017            245 non-null    float64
 52  2018            245 non-null    float64
 53  2019            245 non-null    float64
 54  2020            245 non-null    float64
 55  2021            245 non-null    float64
 56  average_rate    245 non-null    float64
dtypes: float64(53), object(4)
memory usage: 118.6+ KB

In [ ]:
pcrf1=pcrf[['Country Name', 'average_rate']]
pcrf1

                    Country Name  average_rate
0                          Aruba     96.203056
1    Africa Eastern and Southern     52.899081
2                    Afghanistan     28.085734
3     Africa Western and Central     54.108691
4                         Angola     34.111267
..                           ...           ...
261                       Kosovo           NaN
262                  Yemen, Rep.     48.823942
263                 South Africa     88.622194
264                       Zambia     67.949980
265                     Zimbabwe     91.649270

[266 rows x 2 columns]

**TASK2<br>
Create a column named “Latest Population” in “population_of_female.csv” that contains the latest population of females in the country.**

In [ ]:
pof['Latest Population'] = pof.iloc[:, -1]

In [ ]:
pof1=pof[['Country Name', 'Latest Population']]
pof1

                    Country Name  Latest Population
0                          Aruba            56330.0
1    Africa Eastern and Southern        354855082.0
2                    Afghanistan         19844584.0
3     Africa Western and Central        237813580.0
4                         Angola         17452283.0
..                           ...                ...
261                       Kosovo           895801.0
262                  Yemen, Rep.         16313210.0
263                 South Africa         30497646.0
264                       Zambia          9864121.0
265                     Zimbabwe          8449834.0

[266 rows x 2 columns]

**TASK3<br>
What is the weighted average of “average_rate”? The weight should be calculated based on “latest population” of females in the country.**

In [ ]:
lt_pop = pof[['Country Name', '2021']]
df_merge = pd.merge(pcrf, lt_pop, on='Country Name') #merging pcrf and lt_pop on Country Name field

In [ ]:
df_merge['Weighted_Average'] = df_merge['average_rate'] * df_merge['2021_y']

In [ ]:
tot_weighted_sum = df_merge['Weighted_Average'].sum()
tot_pop = df_merge['2021_y'].sum()

In [ ]:
weighted_avg = tot_weighted_sum / tot_pop

In [ ]:
print("Weighted Average of 'average_rate':", weighted_avg)

Weighted Average of 'average_rate': 77.01066757324583

**TASK4<br>
What is the Median of “average_rate”?**

In [ ]:
median_avg_rate = df_merge['average_rate'].median()
print("Median of 'average_rate':", median_avg_rate)

Median of 'average_rate': 90.96608239594593

**TASK5<br>
What is the InterQuartile Range of “average_rate”?**

In [ ]:
# Calculating the 25th and 75th percentiles
Q1 = df_merge['average_rate'].quantile(0.25)
Q3 = df_merge['average_rate'].quantile(0.75)

# Calculating the Interquartile Range
IQR = Q3 - Q1

print("InterQuartile Range of 'average_rate':", IQR)

InterQuartile Range of 'average_rate': 29.470233932725478

**TASK6<br>
 What is the Variance of “average_rate”?**

In [ ]:
var_avg_rate = df_merge['average_rate'].var()

print("Variance of 'average_rate':", var_avg_rate)

Variance of 'average_rate': 512.9310266947465